name: cd

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

permissions:
  contents: read

concurrency:
  group: v${{ inputs.version }}
  cancel-in-progress: true

jobs:
  qa:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - [self-hosted, macOS, X64]
          - [self-hosted, linux, X64]
          - [self-hosted, macOS, ARM64]
          - [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/dev@v0
      - run: deno task dnt

  attach:
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/dev@v0

      - run: deno task dnt ${{ inputs.version }}

      - run: |
          mv dist libpkgx-${{inputs.version}}
          tar cJf libpkgx-${{ inputs.version }}.tar.xz libpkgx-${{inputs.version}}

      - name: attach to release
        run:
          gh release upload
            --clobber
            libpkgx-${{ inputs.version }}.tar.xz
        env:
          # using this token rather than github.token due to `release not found` bug
          # https://github.com/cli/cli/issues/5252
          GH_TOKEN: ${{ secrets.TEMP_JACOBS_GITHUB_PAT }}
          GH_REPO: pkgxdev/libpkgx
